version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - checkout
      - run: cd ./front-end
      - run: npm install
      - run: npm run build
      - run: cd ../back-end
      - run: npm install
      - run: npm test